# Generated by Django 4.1.4 on 2023-03-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='eated_at',
            new_name='created_at',
        ),
    ]
